CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    variant VARCHAR(255),
    sku VARCHAR(255),
    price DECIMAL(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);